name: Workflow Commands
on: [push]

jobs:
    testing-workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting a error message
              run: echo "::error::Faltando Ponto e Virgula"
            
            - name: Setting an error message with params
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Setting an debug message with params
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Setting an warning message with params
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Setting an notice message with params
              run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Group of logs
              run: |
                echo "::group::Meu grupo titulo"
                echo "Teste1"
                echo "Teste2"
                echo "Teste3"
                echo "Teste4"
                echo "Teste5"
                echo "::endgroup::"

            - name: Masking a value
              run: echo "::add-mask::Secret String"

            - name: Echo a secret
              run: echo "Secret String"