name: Workflow Commands
on: [push]

jobs:
    testing-workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting a error message
              run: echo "::error::Faltando Ponto e Virgula"