name: Workflow Commands
on: [push]

jobs:
    testing-workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting a error message
              run: echo "::error::Faltando Ponto e Virgula"
            
            - name: Setting an error message with params
              run: echo "::error title:Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Setting an debug message with params
              run: echo "::debug title:Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Setting an warning message with params
              run: echo "::warning title:Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"
            
            - name: Setting an notice message with params
              run: echo "::notice title:Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Faltando Ponto e Virgula"